version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: org.jetbrains.exposed:exposed-jdbc
    versions:
    - 0.29.1
    - 0.30.1
    - 0.30.2
  - dependency-name: org.jetbrains.exposed:exposed-dao
    versions:
    - 0.28.1
    - 0.30.1
    - 0.30.2
  - dependency-name: org.jetbrains.exposed:exposed-core
    versions:
    - 0.29.1
    - 0.30.1
    - 0.30.2
  - dependency-name: org.jetbrains.exposed:exposed-jodatime
    versions:
    - 0.29.1
    - 0.30.1
    - 0.30.2
  - dependency-name: org.jetbrains.exposed:exposed-java-time
    versions:
    - 0.29.1
    - 0.30.1
    - 0.30.2
  - dependency-name: io.javalin:javalin
    versions:
    - 3.13.3
    - 3.13.4
    - 3.13.5
  - dependency-name: org.jetbrains.kotlin.jvm
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.module:jackson-module-kotlin
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: org.postgresql:postgresql
    versions:
    - 42.2.18
    - 42.2.19
  - dependency-name: com.zaxxer:HikariCP
    versions:
    - 4.0.1
    - 4.0.2
